### ISSUE TITLE
Error installing ioda package urllib3

### ISSUE THREAD

**Issue by rogervieiraa** [yoda-pa/yoda#266]
**What happened**: when I do the install to the venv, I'm getting an error in one package: urllib3 
ERROR:
```
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
```
When I try to execute yoda getting this error:
```
Traceback (most recent call last):
  File "/home/roger/Documents/projetos/yoda/venv/bin/yoda", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/roger/Documents/projetos/yoda/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/roger/Documents/projetos/yoda/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/roger/Documents/projetos/yoda/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/roger/Documents/projetos/yoda/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/roger/Documents/projetos/yoda/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/roger/Documents/projetos/yoda/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.25,>=1.21.1' distribution was not found and is required by requests

```

**What you expected to happen**: install yoda

**How to reproduce it (as minimally and precisely as possible)**: https://github.com/yoda-pa/yoda/blob/master/.github/CONTRIBUTING.md standard way to install

**Anything else we need to know?**:

**Environment**:
- Yoda version (use `yoda version`): can't install
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): Linux
- Others:

/kind bug

**Comment by manparvesh** [comment]
@rogervieiraa I guess we just need to upgrade `requests` versions
