### ISSUE TITLE
Idea list not able to create project

### ISSUE THREAD

**Issue by manparvesh** [yoda-pa/yoda#53]
What are the steps to reproduce this issue?
-------------------------------------------
1. install `yoda`
2. try to create an idea

What happens?
-------------
```
$ yoda ideas add --task "demo text" --project "demo project" --inside "demo inside"                                                                                                                 Brief desc of the current task : 
something and something else
Traceback (most recent call last):
  File "/home/mp/Desktop/github_repos/yoda/venv/bin/yoda", line 11, in <module>
    load_entry_point('yoda', 'console_scripts', 'yoda')()
  File "/home/mp/Desktop/github_repos/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mp/Desktop/github_repos/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mp/Desktop/github_repos/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mp/Desktop/github_repos/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mp/Desktop/github_repos/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mp/Desktop/github_repos/yoda/modules/life.py", line 346, in ideas
    sub_commands[subcommand]((project or inside), task)
  File "/home/mp/Desktop/github_repos/yoda/modules/life.py", line 253, in add_task
    with open(IDEA_CONFIG_FILE_PATH, 'w') as f:
IOError: [Errno 2] No such file or directory: '/home/mp/.yoda/life/ideaconfig.txt'
```

**Comment by ujjaldas1997** [comment]
@manparvesh , thanks for the bug.
I had tried to reproduce the error that you faced. One of the possible reason could be the missing directory in any of the `"/home/mp/.yoda/life/"`
I had tried to change the `"IDEA_CONFIG_FILE_PATH"` little bit to `os.path.join(config_path_prefix, 'life/some_demo/ideaconfig.txt')` instead of `os.path.join(config_path_prefix, 'life/ideaconfig.txt')` and reproduced the following--
```
(venv) ujjaldas223@ujjal:~/projects/yoda$ yoda ideas add --task "demo text" --project "anything" --inside "demo inside"
Brief desc of the current task : 
hello
Traceback (most recent call last):
  File "/home/ujjaldas223/projects/yoda/venv/bin/yoda", line 11, in <module>
    load_entry_point('yoda', 'console_scripts', 'yoda')()
  File "/home/ujjaldas223/projects/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ujjaldas223/projects/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ujjaldas223/projects/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ujjaldas223/projects/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ujjaldas223/projects/yoda/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ujjaldas223/projects/yoda/modules/life.py", line 302, in ideas
    subcommands[subcommand]((project or inside), task)
  File "/home/ujjaldas223/projects/yoda/modules/life.py", line 219, in add_task
    with open(IDEA_CONFIG_FILE_PATH, 'w') as f:
IOError: [Errno 2] No such file or directory: '/home/ujjaldas223/.yoda/life/source/ideaconfig.txt'
```


In other ways, I think it will work fine as(some examples) --
```
(venv) ujjaldas223@ujjal:~/projects/yoda$ yoda ideas add --task "demo text" --inside "demo inside"
Brief desc of the current task : 
Remind me about my homework, submission day is tomorrow
(venv) ujjaldas223@ujjal:~/projects/yoda$ yoda ideas show
demo inside
	demo text
		Remind me about my homework, submission day is tomorrow
(venv) ujjaldas223@ujjal:~/projects/yoda$ yoda ideas add --task "demo text" --inside "demo inside" --project "anything"
Brief desc of the current task : 
hello
(venv) ujjaldas223@ujjal:~/projects/yoda$ yoda ideas show
demo inside
	demo text
		Remind me about my homework, submission day is tomorrow
anything
	demo text
		hello
(venv) ujjaldas223@ujjal:~/projects/yoda$ yoda ideas add --task "demo text" --project "anything" --inside "demo inside"
Brief desc of the current task : 
whatever
(venv) ujjaldas223@ujjal:~/projects/yoda$ yoda ideas show
demo inside
	demo text
		Remind me about my homework, submission day is tomorrow
anything
	demo text
		hello
	demo text
		whatever
```
I also suggest to use either of `--project` or `--inside`, as both of these will direct to project eventually. I used these two names for project, as these may sound convenient as like a normal english sentence, otherwise there is no reason to use both.
Please tell me if I am missing any other things, or you are still getting the same error.

**Comment by manparvesh** [comment]
@ujjaldas1997 thanks for clearing it up! I understand now. This works fine

**Comment by groovychoons** [comment]
I had this same issue, and managed to fix it by adding `create_folder(LIFE_CONFIG_FOLDER_PATH)
` after 
`# config file path
LIFE_CONFIG_FILE_PATH = get_config_file_paths()["LIFE_CONFIG_FILE_PATH"]
LIFE_CONFIG_FOLDER_PATH = get_folder_path_from_file_path(LIFE_CONFIG_FILE_PATH)
`
as I saw `create_folder()` was used in the alias section, which was working well for me.
Perhaps this could be added as a fix to this issue?

**Comment by manparvesh** [comment]
@groovychoons thanks for pointing it out! I will reopen this issue and you or anyone interested can create a PR for this.

**Comment by groovychoons** [comment]
Have submitted a pull request with the fix mentioned earlier :)
